<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoriesWithSubcategories()
    {
        $qb = $this->createQueryBuilder('c')
            ->leftJoin('c.subcategories', 's')
            ->addSelect('s');

        return $qb->getQuery()
            ->getResult();
    }
}
