<?php

namespace AppBundle\Repository;

/**
 * CookingUnityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CookingUnityRepository extends \Doctrine\ORM\EntityRepository
{
}
