<?php

namespace AppBundle\Repository;

/**
 * CookingTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CookingTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
