<?php

namespace AppBundle\Repository;

/**
 * DeviceModeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeviceModeRepository extends \Doctrine\ORM\EntityRepository
{
}
