<?php

namespace AppBundle\Repository;

/**
 * UnityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LiaisonRepository extends \Doctrine\ORM\EntityRepository
{
}
